magick image1.emf     image1.png              
magick image13.emf    image13.png 
magick image14.emf    image14.png 
magick image15.emf    image15.png 
magick image16.emf    image16.png 
magick image17.emf    image17.png 
magick image18.emf    image18.png 
magick image2.emf     image2.png  
magick image3.emf     image3.png  
magick image4.emf     image4.png  
magick image5.emf     image5.png  
magick image6.emf     image6.png  
